### ISSUE TITLE
Error in exact comparison.

### ISSUE THREAD

**Issue by Filipp-Druan** [massung/re#5]
Hello!
I have a problem that when a sample can be unambiguously matched to a stratum, an empty string is stored in re-match.
For example:
```lisp
(match-re "+" "+")
#<RE::RE-MATCH "">
```

Could you please fix this?

**Comment by massung** [comment]
Good find. This is a bug, but the bug is not erroring with an invalid expression. To match against `+` (or other regex characters), you need to escape them with `%`.

```
(match-re "%+" "+")
#<RE::RE-MATCH "+">
```

This is now fixed in the new home location for the `re` (and all my other CL libraries): https://github.com/cl-boost/re. Here is a link to the commit (diff) in case you aren't interested in using that version and want to just update your local code: https://github.com/cl-boost/re/commit/128092fc8e727ded74f144e09230ef4b177abb0c

FYI, the move was made so that all the packages could be renamed to `boost-*` (e.g. `re` -> `boost-re`) so as to no longer conflict with other packages out there in Quicklisp. If you do switch over, be aware of this ASDF module name change.
